title: Ardhan Website
author: ardhanr
email: ardhan.ariframadhan@gmail.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

twitter_username: jekyllrb
github_username:  ardhanr
rss: rss
show_excerpts: false

minima:
  date_format: "%b %-d, %Y"
